import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/nav/Navigation";

import { Catamaran } from "next/font/google";

const catamaran = Catamaran({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
        className={catamaran.className}    >
      <body className="min-h-full flex flex-col">
        <Navigation/>
        {children}
        </body>
    </html>
  );
}
